[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
camerax_version = "1.5.1"
androidx-lifecycle-runtime-compose = "2.9.4"
google-dagger-hilt = "2.57.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version = "1.9.4" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime-compose" }

#--------------timber----------------
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }
#--------------timber----------------


#--------------retrofit----------------
squareup-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version = "3.0.0" }
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version = "5.3.0" }
squareup-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "3.0.0" }
#--------------retrofit----------------



#--------------datastore----------------
androidx-datastore = { group = "androidx.datastore", name = "datastore", version = "1.1.7" }
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
jetbrains-kotlin-seralization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
#--------------datastore----------------


#-------------------- Dagger hilt --------------------
google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-dagger-hilt" }
google-dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "google-dagger-hilt" }
google-dagger-hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "google-dagger-hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.3.0" }
#-------------------- Dagger hilt --------------------

#------------------------Camera X------------------------------
androidx-camera-mlkit-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "camerax_version" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax_version" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax_version" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax_version" }
google-mlkit-barcode = { group = "com.google.mlkit", name = "barcode-scanning", version = "17.3.0" }
androidx-camera-compose = { module = "androidx.camera:camera-compose", version.ref = "camerax_version" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax_version" }
#------------------------Camera X------------------------------


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
dagger-hilt-android-plugin = { id = "dagger.hilt.android.plugin"}
google-devtools-ksp = { id = "com.google.devtools.ksp", version = "2.3.0" }
jetbrains-kotlin-serialization-plugin = {id="org.jetbrains.kotlin.plugin.serialization"}
